### ISSUE TITLE
found a typo in a tag - jbass_eap

### ISSUE THREAD

**Issue by bhirsch70** [samdoran/ansible-role-jboss-eap#3]
Hi guys,
In working with this role, I ran into a small typo and wanted to let you know.

```yaml
- name: ZIP | Extract JBoss EAP zip file to {{ jboss_eap_library_dest }}
  unarchive:
    src: "{{ jboss_eap_download_dir }}/{{ jboss_eap_zip_file | basename }}"
    dest: "{{ jboss_eap_library_dest }}"
    copy: no
    creates: "{{ jboss_eap_jboss_home }}/version.txt"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    mode: 0755
  register: jboss_install
  tags:
    - jbass_eap
```
